// dunload.h
//

#pragma once

#include <memory>

#define DRLG1_NUM_RANDOM_PIECES 2

enum DungeonLevelId {
	DUNGEON_TOWN,
	DUNGEON_NEWRND1,
	DUNGEON_NEWRND2,
	DUNGEON_BUTCHER_LAIR,
	DUNGEON_BUTCHER,
	DUNGEON_SKELKING_ENTRANCE,
	DUNGEON_SKELKING_PREL1,
	DUNGEON_SKELKING_L1,
	DUNGEON_FOULWATER_PREL3,
	DUNGEON_FOULWATER_L3,
	DUNGEON_BANNER,
	DUNGEON_BANNER_MONSTERS,
	DUNGEON_HALLOFBLIND,
	DUNGEON_HALLOFBLIND_MONSTERS,
	DUNGEON_MAZE_PRE1,
	DUNGEON_MAZE_L1,
	DUNGEON_BONECHAMBER_PREL2,
	DUNGEON_BONECHAMBER_L2,
	DUNGEON_ANVIL_MONSTERS,
	DUNGEON_VALOR,
	DUNGEON_VALOR_MONSTERS,
	DUNGEON_CHAMBEROFBONE,
	DUNGEON_CHAMBEROFBONE2,
	DUNGEON_WARLORD,
	DUNGEON_WARLORD_MONSTERS,
	DUNGEON_WARLORD2,
	DUNGEON_VILE,
	DUNGEON_VILE_MONSTERS,
	DUNGEON_VILE_PREL1,
	DUNGEON_VILE_L1,
	DUNGEON_DIABLOQUAD1,
	DUNGEON_DIABLOQUAD1_MONSTERS,
	DUNGEON_DIABLOQUAD2_MONSTERS,
	DUNGEON_DIABLOQUAD2A,
	DUNGEON_DIABLOQUAD2B,
	DUNGOEN_DIABLOQUAD3_MONSTERS,
	DUNGEON_DIABLOQUAD3A,
	DUNGEON_DIABLOQUAD3B,
	DUNGOEN_DIABLOQUAD4_MONSTERS,
	DUNGEON_DIABLOQUAD4A,
	DUNGEON_DIABLOQUAD4B
};

std::unique_ptr<uint16_t[]> LoadLevelSetPiece(DungeonLevelId levelId);
